version: "3.9"

services:
  docker-api:
    container_name: docker-api
    hostname: docker-api
    build:
      context: .
      dockerfile: docker/Dockerfile

    networks:
      - shared-network
    ports:
      - "8000:8000"
    env_file:
      - .env

    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  shared-network:
    external: true